version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - anio
  - anios
  - Aritmeticos
  - Asignacion
  - calificacion
  - caracter
  - celsius
  - codigo
  - Comparacion
  - CUCEI
  - decrementarlo
  - dias
  - digito
  - digitos
  - farenheit
  - Farenheit
  - gan√°
  - Inscripcion
  - Jeshua
  - kilometro
  - kilometros
  - Logicas
  - Miercoles
  - Multiplicacion
  - numeros
  - parametros
  - rectangulo
  - Reynozo
  - Sabado
  - sobreescritura
  - tendra
  - terminos
  - ULAM
ignoreWords: []
import: []
